Run app metrics resiliency tests last
The app metrics resiliency tests intentionally break `aiokafka` clients
in an unclean way. When the aiokafka objects get garbage collected,
Python asyncio logs warning messages that task exceptions were never
retrieved, like this:

```
asyncio:base_events.py:1879 Future exception was never retrieved
future: <Future finished exception=NodeNotReadyError('Attempt to send a request to node which is not ready (node id 1).')>
aiokafka.errors.NodeNotReadyError: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 1).```

The time that this logging happens is not deterministic. It can mess up
other tests, like tests of the Sentry functionality because the log
messages get picked up by the mock Sentry transport if they happen after
the Sentry fixtures have initialized:

https://github.com/lsst-sqre/safir/actions/runs/19583537252/job/56087067160

There may be a way to deterministically and cleanly cancel these failed
tasks, or it may be a bug in the aiokafka library, but until we figure
it out, run these last to make sure they don't infect other tests.